### ISSUE TITLE
Unable to generate token

### ISSUE THREAD

**Issue by zbikmarc** [coreos/discovery.etcd.io#10]
Im not sure if this is an issue or my lack of knowledge but I can not get my own discovery.etcd.io running. I need discovery service in private network (no access to https://discovery.etcd.io). I cloned git repository into one of my machines (ubuntu), installed go lang and run devweb executable.

When I issue  ```curl -v -X PUT localhost:8087/new``` I got:
```
$ curl -v -X PUT localhost:8087/new
* Adding handle: conn: 0x2041b10
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x2041b10) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 8087 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8087 (#0)
> PUT /new HTTP/1.1
> User-Agent: curl/7.32.0
> Host: localhost:8087
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 25
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 25 Sep 2014 15:12:51 GMT
<
Unable to generate token
```

and on devweb logs:
```
setupToken returned: Couldn't setup state <nil> 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
127.0.0.1 - - [25/Sep/2014:17:01:36 +0200] "PUT /new HTTP/1.1" 400 25
```

I tried to do some debugging and it looks like it fail CreateDir function in line 32 in file ```handlers/new.go```
```go
resp, err := client.CreateDir(key, 0)
```

Thank you in advance for help

**Comment by fropdeployer** [comment]
@zbikmarc, as managed to generate the key?
I'm having the same problem as yours.

**Comment by zbikmarc** [comment]
@fropdeployer I did not :(
I had to drop that idea, at least for a while.

**Comment by fropdeployer** [comment]
@philips, okay ? 

Is there any way to make the Discovey work?
I need to create a Correos cluster on a network, you may not have internet access.
With so I can not access the https://discovery.etcd.io ..

thank you,

**Comment by philips** [comment]
@fropdeployer See this: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#etcd-discovery

Sorry for the delay.

**Comment by discotroy** [comment]
I'm having the same problem.  I pulled the Docker image and ran that, but get a 401 with the error message "Unable to generate token".

I pull the source and made the modification mentioned above, too, but still the same error.

Does anyone have any suggestions as to what I might be doing wrong?

**Comment by wptad** [comment]
@discotroy  It seems etcd service problem. Discovery.etcd.io cannot work without etcd ?

**Comment by kriss9** [comment]
Unable to generate token as well. Where's the working example of private discovery?

**Comment by isaiah** [comment]
have the same problem here, running in docker on ElasticBeanstalk.

**Comment by wptad** [comment]
@isaiah  

Here is my usage: <https://github.com/wptad/coreos-management/blob/master/discovery.md>

**Comment by reiz** [comment]
Why was this ticket closed? As far as I can see many people still have the issue that this is running like documented in the README.

**Comment by exolain** [comment]
Was anyone able to fix this issue? I'm having the same problem

**Comment by jescarri** [comment]
has anyone fixed the problem? it also seems that it doesn't like to be mapped with -p 80:8087 or be put behind a loadbalancer, also does anyone has managed to specify the base url? with -host? any time I try to do it, it panics.

**Comment by jescarri** [comment]
````
docker run --net=host quay.io/coreos/discovery.etcd.io -host=<FQDN>
panic: Unexpected number of socket activation fds

goroutine 1 [running]:
main.main()
	/usr/src/myapp/third_party/src/github.com/coreos/discovery.etcd.io/discovery.go:29 +0x12b

goroutine 2 [runnable]:
runtime.forcegchelper()
	/usr/src/go/src/runtime/proc.go:90
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
	/usr/src/go/src/runtime/mgc0.go:82
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
	/usr/src/go/src/runtime/malloc.go:712
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
`````

**Comment by mmeroberts** [comment]
I am still having this problem.  Is there any solution to this.  I followed the instructions on the discovery.io page and tried alternative images but to no avail?
