### ISSUE TITLE
Support CORS headers for web browsers

### ISSUE THREAD

**Issue by seidtgeist** [coreos/discovery.etcd.io#12]
I noticed that https://discovery.etcd.io/new doesn't respond with CORS (Cross Origin Resource Sharing) headers:

```
$ curl -i -w "\n" https://discovery.etcd.io/new
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Thu, 02 Oct 2014 09:55:23 GMT
Content-Length: 58
Connection: keep-alive

https://discovery.etcd.io/$token
```

This means that JS web apps on different domains are unable to get discovery tokens from https://discovery.etcd.io/new. If browsers were able to get tokens, some interesting possibilities would pop up (I'm using DO as an example):
1. Get unique discovery token from https://discovery.etcd.io/new
2. Perform OAuth authentication against DO to get an OAuth Access Token
3. Create new DO droplets with the CoreOS image via their API by POSTing the cloud-config as user data. The cloud-config would include the discovery token generated in (1)

What this basically means: Setting up a CoreOS cluster from a web browser without any setup and just a few clicks. Pretty cool. My motivation for this is a browser based editor I'm working on. It generates tarball archives and sends them to dockerd for building. Being able to set up a (development) CoreOS cluster from a browser with a few clicks would be a first step towards cluster awareness in the dev environment.

DO has good CORS support which is documented [here](https://developers.digitalocean.com/v2/#cors).

**Comment by blakelapierre** [comment]
+1

Will look at code to see what needs to be done, but this is definitely a blocker for many interesting use cases. Alternative is to setup a proxy, which I really don't want to do, but it looks like I will have to temporarily.

BTW, Docker pulled CORS from Docker Hub last week. I've a support ticket in, but doesn't seem to be going anywhere...

**Comment by EgoAleSum** [comment]
:+1: I'm writing a web app that generates a config file for etcd2. The app runs in any web browser. In the app, I'm making an async request to https://discovery.etcd.io/new to generate a new token, but that request fails because the Access-Control-Allow-Origin header is missing.

Could you add a header for CORS so the /new endpoint can be called by anywhere?

**Comment by philips** [comment]
@colhom there is a discussion on this on HN today. Probably should take another look at adding this header on the LB.

**Comment by colhom** [comment]
@philips: CORS from anywhere for /new on discovery.io has me worried. that's a write operation that we'd be opening up to any javascript code served on the internet. i feel like we're asking for a browser based ddos filling up our etcd cluster.

I feel like, if we're doing CORS from anywhere, we should put in a Referrer header based rate-limit cap on the `/new` endpoint. If certain domains want to exceed the limit legitimately, we'll have a white-list that exempts domains from the cap.

Thoughts?

\cc @EgoAleSum

**Comment by blakelapierre** [comment]
DDOS is a legitimate concern, however, the endpoint is already susceptible. Accepting compliant CORS traffic would allow conforming agents to interact with the service. Non-conforming agents and non-browser HTTPS users can already access the endpoint.

A domain-based rate-limit seems reasonable, but it would be nice if you could afford to limit by the sending address. I think there might also be a "reverse-ddos" attack where the referrer is spoofed to exceed the rate of a domain.

**Comment by gtank** [comment]
@colhom is on the right track here.

The DoS risk isn't affected much by this, but wildcard CORS opens new horizons in **D**DoS. Malicious actors who can MitM web traffic can inject Javascript, causing browsers to become attack nodes. See for example China's ["Great Cannon"](https://citizenlab.org/2015/04/chinas-great-cannon/) system that was used against Github last year.

If we're going to wildcard we should implement rate limiting at the same time.
