### ISSUE TITLE
use Godeps

### ISSUE THREAD

**Issue by philips** [coreos/discovery.etcd.io#14]
Get rid of third_party.go and just use Godeps instead.

**Comment by madharjan** [comment]
Is this correct replacement of thirtd_party.go with Godeps!?

b8709784927bab2b3b990cf5f45908c36f11c866

Following works
```
./devweb

docker build -t coreos/discovery.etcd.io .
```
`./build` and  `./devweb` does `go install`on Godeps and Devweb - is this right?

**Changes**
Delete:
* build-docker
* third_party.go
* third_party/

Added:
* Godeps/
* .godir

Updated
* build
* devweb
* Dockerfile

**Comment by krish7919** [comment]
Hi, I am trying to put in a PR for this, but I get an error:
godep save ./...
godep: Package (code.google.com/p/rsc/devweb/slave) not found

So obviously, I do a `go get`:
go get code.google.com/p/rsc/devweb/slave
package code.google.com/p/rsc/devweb/slave: unable to detect version control system for code.google.com/ path

Can someone help me here?

**Comment by tschuy** [comment]
#40 switches to go vendoring instead, which replaces godeps.
