### ISSUE TITLE
maybe something wrong

### ISSUE THREAD

**Issue by alexwhen** [coreos/discovery.etcd.io#29]
sudo ./devweb
Password:
setupToken returned: Couldn't setup state <nil> 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
127.0.0.1 - - [02/Jun/2015:12:04:57 +0800] "PUT /new HTTP/1.1" 400 25

curl --verbose -X PUT localhost:8087/new
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8087 (#0)
> PUT /new HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8087
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 25
< Content-Type: text/plain; charset=utf-8
< Date: Tue, 02 Jun 2015 04:04:58 GMT
<
Unable to generate token
* Connection #0 to host localhost left intact

**Comment by tschuy** [comment]
in #43 you can now specify the url of your etcd cluster to connect to with `--etcd`, which should resolve this problem.
