### ISSUE TITLE
Discovery base URL should be configurable

### ISSUE THREAD

**Issue by brianredbeard** [coreos/discovery.etcd.io#3]
Right now setting up a discovery service for behind the firewall use will force an incorrect host name:
 
https://github.com/coreos/discovery.etcd.io/blob/3518a61804a5dafbea09b39cd2a85ec911bec10a/handlers/new.go#L64

**Comment by jedsmith** [comment]
@philips merged my fix, so this works now with `--host`:

    bin/discovery.etcd.io --host=https://behind-firewall.example.net
