### ISSUE TITLE
Migrate to etcd clientv3

### ISSUE THREAD

**Issue by colhom** [coreos/discovery.etcd.io#52]
\cc @xiang90 @heyitsanthony

**Comment by colhom** [comment]
For context, etcd-operator does not support automated back-up for applications using v2 API. We wish to operate discovery.etcd.io with etcd-operator, and this path was mentioned by @xiang90 as being reasonable.

**Comment by brianredbeard** [comment]
Is this going to be acceptable with how discovery works?  IIRC discovery is basically just an HTTP proxy/router.  In the past (in discussing the move to GRPC) this was deemed as both unnecessary for etcd v3 as well as impossible with how the service currently works.

**Comment by heyitsanthony** [comment]
Another migration path we've discussed is loosely emulating v2 over v3.

**Comment by philips** [comment]
Moved to https://github.com/etcd-io/etcd/pull/10627

**Comment by philips** [comment]
done
