### ISSUE TITLE
problem with certificates of https://discovery.etcd.io going through proxy

### ISSUE THREAD

**Issue by wu105** [coreos/discovery.etcd.io#59]
I am setting up a clustered etcd with a discovery token in the form of  https://discovery.etcd.io/blahblah.
The etcd is stuck with the following error::

2018-03-06 03:28:56.509265 E | discovery: error #0: x509: failed to load system roots and no roots provided
2018-03-06 03:28:56.509289 I | discovery: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2s

The certificate is extracted using openssl s_client command shown at the end.  The certificate is good for curl:

curl --cacert /etc/pki/ca-trust/source/anchors/discovery.etcd.io.crt https://discovery.etcd.io
<a href="https://coreos.com/docs/cluster-management/setup/cluster-discovery/">Moved Permanently</a>.

But the same certificate does not work for wget:

wget --ca-certificate /etc/pki/ca-trust/source/anchors/discovery.etcd.io.crt https://discovery.etcd.io
--2018-03-05 22:27:50--  https://discovery.etcd.io/
Resolving discovery.etcd.io (discovery.etcd.io)... 54.183.250.138, 52.9.105.182
Connecting to discovery.etcd.io (discovery.etcd.io)|54.183.250.138|:443... connected.
ERROR: cannot verify discovery.etcd.io's certificate, issued by ‘/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscaler.net)/emailAddress=support@zscaler.com’:
  unable to get issuer certificate
To connect to discovery.etcd.io insecurely, use `--no-check-certificate'.

The above certificate is added to the system bundle file /etc/pki/tls/certs/ca-bundle.crt on Oracle Linux, a variation of RedHat.  That satisfies curl.

The etcd container runs on kubernetes, using a yaml file from https://kubernetes.io/docs/admin/high-availability/etcd.yaml with minor changes.  All the local pathes in this yaml file are mounted  exactly as in that yaml file:
            
      path: /etc/ssl        certs/ca-bundle.crt
      path: /usr/share/ssl
      path: /var/ssl
      path: /usr/ssl
      path: /usr/lib/ssl   
      path: /usr/local/openssl
      path: /etc/openssl  ca-bundle.crt
      path: /etc/pki/tls    certs/ca-bundle.crt

The ca bundle is accessible via two of the paths by default, the first and last in the above list.  I also added the bundle file to the /etc/openssl directory to no avail.  

The etcd image used is container-registry.oracle.com/kubernetes/etcd-amd64:3.0.17, supposed to be the same as the official image.

Outupt of `openssl s_client -connect discovery.etcd.io:443 -verify 5 -showcerts` is the following and its entity is used as the  certificate:
```
CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=discovery.etcd.io
   i:/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscaler.net)/emailAddress=support@zscaler.com
-----BEGIN CERTIFICATE-----
MIID8TCCAtmgAwIBAgIQAl3wbwKWzGFUEWmlSOxPoDANBgkqhkiG9w0BAQsFADCB
qTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFTATBgNVBAoTDFpz
Y2FsZXIgSW5jLjEVMBMGA1UECxMMWnNjYWxlciBJbmMuMTMwMQYDVQQDEypac2Nh
bGVyIEludGVybWVkaWF0ZSBSb290IENBICh6c2NhbGVyLm5ldCkxIjAgBgkqhkiG
9w0BCQEWE3N1cHBvcnRAenNjYWxlci5jb20wHhcNMTcxMjA4MDAwMDAwWhcNMTkw
MTA4MTIwMDAwWjAcMRowGAYDVQQDExFkaXNjb3ZlcnkuZXRjZC5pbzCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ0WwyAJ0tglwqkurRPiHqx8kkSO4vmk
uA9Z4OyaYmzmORpAJZrZZ3xMS8r67YxsZkLwAEs6zy51RDtxDn64GnOhj33yct5r
UE+2fXq+YnoGx8pftWOBuW0UmESJ1hfLIds8XPr7svbx/OlQVjAWwKQdhOgxuBSz
wShDJYSrvo6ylh6MylrMUUOIIMM3o0MamnH/FkEx40/60FQuedi8OfkwayJIodD4
mMAMlxFIAq3uaZk7f3Stwo8HIe2BKoZeCnu6GcEMoHZHBJFkFpFkLExDEvnA+wWX
0asF4/x2G1s9MjMf7hNEa5Mnns7YwEs5JosA+PvmOtNZ4bi4jXic8SkCAwEAAaOB
oDCBnTAcBgNVHREEFTATghFkaXNjb3ZlcnkuZXRjZC5pbzAOBgNVHQ8BAf8EBAMC
BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
QAYDVR0fBDkwNzA1oDOgMYYvaHR0cDovL2dhdGV3YXkuenNjYWxlci5uZXQvenNj
YWxlci16c2NybC0tNC5jcmwwDQYJKoZIhvcNAQELBQADggEBAHhhWrm9NiC8kNM5
VLFvPOMo67Gj2sngX+qBXgcbQ2NU5GWJ+lfYCdyiLpA5i9LLCOoOi3YGrGp06qfz
uPR3RXyacS4DpVUF2q1MANMwSe1hQmq0KLZkBpJYjjZvfnv6QlHDoecM/yUcnmXY
iujGq22xFh6HcYy4WvCZXUA0lWiiVePcAJwobilXtvyCrmPLsNpsqql1Kjo9EQ5g
mkcqjAxRutIzk9lVKG7WPT8IoJfKeZ0q1+t+CNZO/9wY1VxfzwYgzjsmIyDy66Yy
d07hM7YDRoa9+Tqhya2+uDabVGmjwUvaU8bZ4ybyp4BVPdZru7LWJG61LaMUqjNv
9jRTOsI=
-----END CERTIFICATE-----
 1 s:/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscaler.net)/emailAddress=support@zscaler.com
   i:/C=US/ST=California/L=San Jose/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Root CA/emailAddress=support@zscaler.com
-----BEGIN CERTIFICATE-----
MIIEBDCCAuygAwIBAgICd3wwDQYJKoZIhvcNAQELBQAwgaExCzAJBgNVBAYTAlVT
MRMwEQYDVQQIEwpDYWxpZm9ybmlhMREwDwYDVQQHEwhTYW4gSm9zZTEVMBMGA1UE
ChMMWnNjYWxlciBJbmMuMRUwEwYDVQQLEwxac2NhbGVyIEluYy4xGDAWBgNVBAMT
D1pzY2FsZXIgUm9vdCBDQTEiMCAGCSqGSIb3DQEJARYTc3VwcG9ydEB6c2NhbGVy
LmNvbTAeFw0xNTAxMDYyMjM2MzRaFw00MjA1MjMyMjM2MzRaMIGpMQswCQYDVQQG
EwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEVMBMGA1UEChMMWnNjYWxlciBJbmMu
MRUwEwYDVQQLEwxac2NhbGVyIEluYy4xMzAxBgNVBAMTKlpzY2FsZXIgSW50ZXJt
ZWRpYXRlIFJvb3QgQ0EgKHpzY2FsZXIubmV0KTEiMCAGCSqGSIb3DQEJARYTc3Vw
cG9ydEB6c2NhbGVyLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AJ0WwyAJ0tglwqkurRPiHqx8kkSO4vmkuA9Z4OyaYmzmORpAJZrZZ3xMS8r67Yxs
ZkLwAEs6zy51RDtxDn64GnOhj33yct5rUE+2fXq+YnoGx8pftWOBuW0UmESJ1hfL
Ids8XPr7svbx/OlQVjAWwKQdhOgxuBSzwShDJYSrvo6ylh6MylrMUUOIIMM3o0Ma
mnH/FkEx40/60FQuedi8OfkwayJIodD4mMAMlxFIAq3uaZk7f3Stwo8HIe2BKoZe
Cnu6GcEMoHZHBJFkFpFkLExDEvnA+wWX0asF4/x2G1s9MjMf7hNEa5Mnns7YwEs5
JosA+PvmOtNZ4bi4jXic8SkCAwEAAaM8MDowHQYDVR0OBBYEFIedbYoiBqnrqKCA
ddzKcd2UWyisMAwGA1UdEwQFMAMBAf8wCwYDVR0PBAQDAgH+MA0GCSqGSIb3DQEB
CwUAA4IBAQAxt5rXlBIJqS4pYyoitWk1SqNNQnkH0pnMJrtnPlAPosXvRWvtEosx
pgYsSOoEKPqQ7hYxSUITc2cUBEBco0FK/2e73L0dSqeMi8hMMnSR8+YFC96n92R4
wtE+uRuY307xKkmIufaSbBNrJoo82HkZ6dGD2J6SbyzfGKQoTDNQBfvk1mYeafxW
7fvExvq6WlVnAJTeg0J5yGg4TWHU2WpgOgG1N3fqCxfAwvlD3uwUYrYgb3mNItCS
M4GYCkCPrwDV0VsLMsmYwtS8U4/jiWfd5Gf43mrkIDobb2Jf6RQpfHOs5xHJDxOj
yzkPMM6VQRmc92J+EH0+7xLErab7E7mg
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=discovery.etcd.io
issuer=/C=US/ST=California/O=Zscaler Inc./OU=Zscaler Inc./CN=Zscaler Intermediate Root CA (zscaler.net)/emailAddress=support@zscaler.com
---
No client certificate CA names sent
---
SSL handshake has read 2182 bytes and written 633 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: E2971174441E002FF39B54039F14784B3724284A89190FC167BFC33DF9C9F5D0A1C49117A930CCB5B9CBDAAA81AAC996
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1520298351
    Timeout   : 300 (sec)
    Verify return code: 2 (unable to get issuer certificate)
---
```

**Comment by lucab** [comment]
It looks like your etcd container is having problems either while picking up the custom CA or while trying to walk the trust chain. This does not seem to involve any CoreOS specific bits (proxied network setup, custom CA chain and third-party container images are outside of our control).

I'd suggest to ask you infrastructure team for recommendations and debugging tips on how to configure applications in your setup. If you are still stuck, you may try asking for community help in one of the etcd forums. I'd also suggest to double-check the location and content of your custom CA bundle.

**Comment by wu105** [comment]
We are using container-registry.oracle.com/kubernetes/etcd-amd64:3.0.17, should be the same as the official image.
It seems that this image finds /etc/ssl/ca-bundle.pem despite the fact that the ca bundle paths for all possible linux distro are mounted.  The etcd image does not pickup the standard ca-bundle for the Fedora flavor of Linux that we are using, where the /etc/ssl/ca-bundle.pem is not populated.
Also the ca bundle has to be good enough for wget -- what is sufficient for curl is not good enough.
Maybe the doc can use some update as to where it is looking for the CA bundles and what needs to be in the CA bundle.
