### ISSUE TITLE
Update and improve discovery service

### ISSUE THREAD

**Issue by joelegasse** [coreos/discovery.etcd.io#61]
This service hasn't seen much attention in recent years, and it's time to fix that.

After talking with @hexfusion about https://github.com/coreos/etcd/issues/9978, we decided on an approach that we think should let us update the service to use the v3 backend.

- [x] Add tests to ensure that improvements/refactoring don't break anything
- [x] Map out current API calls and endpoints
- [x] Add a true handler for each endpoint, rather than the current proxy
- [x] Convert the current logic to a v2 "backend"
- [x] Add a v3 backend, and allow for reading from the v2 backend first
- [ ] Add a TTL to clusters to prevent data from growing unbounded over time

At that point, we will probably call the discovery service "version 3", and begin strongly encouraging people to run their own discovery services, and not rely directly on the publicly hosted instance.

**Comment by philips** [comment]
I want to add the TTL to https://github.com/etcd-io/etcd/pull/10627 before deploying it. I think I am just going to add a secondary index with timestamps for a deletion date.
